### ISSUE TITLE
Cancelation results for hints not handled properly

### ISSUE THREAD

**Issue by iainmcgin** [openid/OpenYOLO-Android#65] opened 2017-06-17 05:51 UTC
I see an exception thrown by validation that appears to be incorrectly handling results that do not include a Hint value, such as when the user cancels the Hint flow.

**Comment by dxslly** [comment] 2017-08-22 04:51
Looks like this is duplicate of https://github.com/openid/OpenYOLO-Android/issues/49.

Closing for now.

**Closed by dxslly** 2017-08-22 04:51 UTC
Labels: bug
